apiVersion: apps/v1
kind: Deployment
metadata:
  name: aritra-eks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aritra-eks-demo
  template:
    metadata:
      labels:
        app: aritra-eks-demo
    spec:
      containers:
      - name: aritra-eks-demo
        image: 096400694479.dkr.ecr.ap-south-1.amazonaws.com/ecr-eks-demo:adc6a3a  # Update this line
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        env:
          - name: DYNAMODB_TABLE_NAME
            value: "aritra_eks_demo"
